// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbvapsvlpkrepypbwoyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJidmFwc3ZscGtyZXB5cGJ3b3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxODU5NjMsImV4cCI6MjA1OTc2MTk2M30.cxGyJ7YAgOMD_0uf9A5kDRGl2AhhGZ1u7ZxkVrlfmFE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);